export const MOVIE_GET_REQUEST = "MOVIE_GET_REQUEST";
export const MOVIE_GET_SUCCESS = "MOVIE_GET_SUCCESS";
export const MOVIE_GET_FAIL = "MOVIE_GET_FAIL";

export const MOVIE_UPCOMING_REQUEST = "MOVIE_UPCOMING_REQUEST";
export const MOVIE_UPCOMING_SUCCESS = "MOVIE_UPCOMING_SUCCESS";
export const MOVIE_UPCOMING_FAIL = "MOVIE_UPCOMING_FAIL";
